media: media
content:
  - name: projects
    label: Projects
    type: collection
    path: 'src/projects/markdowns'
    view:
      fields: [ title, published ]
    fields:

      - name: published
        type: boolean
        default: false

      - name: title
        type: string

      - name: slug
        type: string

      - name: description
        type: string

      - name: subdomains
        type: select
        options:
          values:     
          - value: swe
            label: SWE
          - value: game
            label: GAME
          - value: swe game
            label: ALL
            
      - name: date
        type: date

      - name: body
        type: rich-text